import Head from "next/head";
import styles from "../styles/Home.module.css";
import axios from "axios";
import { useState } from "react";
import { Record } from "../components/Record";
import Accordion from "@mui/material/Accordion";
import AccordionDetails from "@mui/material/AccordionDetails";
import AccordionSummary from "@mui/material/AccordionSummary";
import Typography from "@mui/material/Typography";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";

const apiUrl: string =
  "https://pudmp6ay0h.execute-api.ap-southeast-2.amazonaws.com/blackheath";

const northSector = 12;

const cf = {
  "rpmToMs": 60,
  "knots": 1.94384,
  "km/h": 3.6,
  "m/s": 1,
};

export const Home = () => {
  const [expanded, setExpanded] = useState<string | false>("0");

  const handleChange =
    (panel: string) => (event: React.SyntheticEvent, isExpanded: boolean) => {
      setExpanded(isExpanded ? panel : false);
    };

  const getData = async () => {
    if (apiUrl) {
      await axios.get(apiUrl).then((response) => {
        if (response.status === 200 || response.statusText === "OK") {
          setTableData(response.data);
          setDataLoaded(true);
        }
      });
    } else return [];
  };

  type Observation = {
    time: string;
    RPMMax: number;
    RPMMin: number;
    RPMAverage: number;
    sectorData: number[];
  }

  const [tableData, setTableData] = useState<Observation[]>([]);
  const [dataLoaded, setDataLoaded] = useState(false);
  const [units, setUnits] = useState("m/s");

  if (!dataLoaded) {
    getData();
  }

  return (
    <div className={styles.container}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/frontEnd/public/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>
          Mt Blackheath Wind Observations
        </h1>
        <div style={{display: "flex", width: "200px", justifyContent: "space-between", alignItems: "center"}}>
          <p>Units: </p>
          <div>
            <button onClick={() => setUnits("m/s")}>m/s</button>
            <button onClick={() => setUnits("knots")}>knots</button>
            <button onClick={() => setUnits("km/h")}>km/h</button>
          </div>
        </div>
        {tableData.length === 0 ? <h3>Loading...</h3> : 
          tableData.map((entry, index) => (
            <Accordion
              expanded={expanded === index.toString()}
              key={index}
              onChange={handleChange(index.toString())}
            >
              <AccordionSummary
                expandIcon={<ExpandMoreIcon />}
                aria-controls="panel1bh-content"
                id="panel1bh-header"
              >
                <Typography sx={{ width: "33%", flexShrink: 0 }}>
                  {entry.time}
                </Typography>
              </AccordionSummary>
              <AccordionDetails>
              <Record
                key={index}
                data={entry}
                units={units}
                cf={cf}
                northSector={northSector}
              />
              </AccordionDetails>
            </Accordion>
          ))}
      </main>
    </div>
  );
};

export default Home;
