import Head from "next/head";
import styles from "../styles/Home.module.css";
// import { DataTable } from "../components/DataTable";
import axios from "axios";
import { useState } from "react";
import { Record } from "../components/Record";

const northSector: number = 12;

export const Home = () => {
  const apiUrl: string =
    "https://pudmp6ay0h.execute-api.ap-southeast-2.amazonaws.com/blackheath";

  const getData = async () => {
    if (apiUrl) {
      await axios.get(apiUrl).then((response) => {
        if (response.status === 200 || response.statusText === "OK") {
          setTableData(response.data);
          setDataLoaded(true);
        }
      });
    } else return [];
  };

  const [tableData, setTableData] = useState([]);
  const [dataLoaded, setDataLoaded] = useState(false);

  if (!dataLoaded) {
    getData();
  }

  return (
      <div className={styles.container}>
        <Head>
          <title>Blackheath Wind Meter</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/frontEnd/public/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <h1 className={styles.title}>
            Mt Blackheath glider launch wind observations
          </h1>
        {tableData.length > 0 && <Record data={tableData[0]} northSector={northSector}/> }
{/* {tableData.length > 0 && tableData.map((entry, index) => <Record key={index} data={entry} northSector={northSector}/> )} */}
        </main>
        
      </div>
  );
};

export default Home;
