name: "CI dev"

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Generate file hash and rename
        run: |
          # Find all .js files and generate a hash
          for file in ./frontEnd/*.js; do
            FILE_HASH=$(sha256sum "$file" | cut -d ' ' -f 1)
            NEW_NAME="$(basename "$file" .js).${FILE_HASH}.js"
            mv "$file" "./frontEnd/$NEW_NAME"
            
            # Update references in HTML files
            for html in ./frontEnd/*.html; do
              sed -i "s/$(basename "$file")/$NEW_NAME/g" "$html"
            done
          done

      - name: Sync to S3
        run: aws s3 sync ./frontEnd s3://mtblackheathwind-test --delete
